[package]
name = "pg_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"

[dev-dependencies]
ctor = "0"
postgresql_commands = "0"
postgresql_embedded = { version = "0", features = ["tokio", "rustls"] }
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0"
tokio-util = { version = "0", features = ["compat"] }
