[package]
name = "pg_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10"
tokio = { version = "1.47", default-features = false, features = ["io-util"] }

scram = "0.6" # TODO: Find a better library or roll own with choice between aws-lc-rs and ring

[dev-dependencies]
aws-lc-rs = "1"
base64 = "0"
ctor = "0"
postgresql_commands = "0"
postgresql_embedded = { version = "0", features = ["tokio", "rustls"] }
tempfile = "3"
rustls = { version = "0", features = ["aws-lc-rs"] }
tokio = { version = "1", features = ["full"] }
tokio-rustls ={ version = "0", features = ["aws-lc-rs"] }
