[package]
name = "pg_stream"
version = "0.1.0"
edition = "2024"

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
bytes = "1.10.1"
tokio = { version = "1.47.1", optional = true, features = ["io-util"] }
