[package]
name = "pg_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"

[dev-dependencies]
pg-embed = { version = "0", default-features = false, features = ["rt_tokio"] }
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0", features = ["compat"] }
