[package]
name = "pg_stream"
version = "0.1.0"
edition = "2024"
authors = ["Taylor Neely <tneely417@gmail.com>"]
description = "A low-level, zero-overhead Rust implementation of the Postgres wire protocol."
repository = "https://github.com/tneely/pg_stream"
readme = "README.md"
license-file = "LICENSE"
keywords = ["postgresql"]
categories = ["database"]

[features]
default = ["startup"] 
startup = ["scram"]

[dependencies]
bytes = "1.10"
tokio = { version = "1.47", default-features = false, features = ["io-util"] }

scram = { version = "0.6", optional = true } # TODO: Find a better library or roll own with choice between aws-lc-rs and ring

[dev-dependencies]
aws-lc-rs = "1"
base64 = "0"
criterion = "0"
ctor = "0"
postgresql_commands = "0"
postgresql_embedded = { version = "0", features = ["tokio", "rustls"] }
tempfile = "3"
rustls = { version = "0", features = ["aws-lc-rs"] }
tokio = "1"
tokio-rustls ={ version = "0", features = ["aws-lc-rs"] }

[[bench]]
name = "pgstream_bench"
harness = false
