[package]
name = "pg_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"

[dev-dependencies]
aws-lc-rs = "1"
base64 = "0"
ctor = "0"
postgresql_commands = "0"
postgresql_embedded = { version = "0", features = ["tokio", "rustls"] }
tempfile = "3"
rustls = { version = "0", features = ["aws-lc-rs"] }
tokio = { version = "1", features = ["full"] }
tokio-rustls ={ version = "0", features = ["aws-lc-rs"] }
tokio-util = { version = "0", features = ["compat"] }
